[mysql]
host = "localhost"
password = "123456"
user = "root"
port = 3306
db = "dbname"
maxOpenConns = 100
maxIdleConns = 10

[bucket]
region = "xxx"
accessKey = "xxx"
secretKey = "xxx"
bucketName = "xxx"
oldBucketName = "xxx"
filePath = "/xxx/xxx/"


[filter]
workNum = 50
tableName = "xxx"
columnName = "xxx"
splitFilter = "-"
apiId = "xxx"
imageBoundsDx = 400
imageBoundsDy = 400